name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest
      - name: Install
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Test
        run: bun run test
      - name: Audit
        run: bun audit
